spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 73699rxy
  jpa:
    hibernate:
      ddl-auto: update